[project]
name = "autogen-workflow"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "autogen>=0.8.5",
    "markdownify>=1.1.0",
    "openai>=1.71.0",
    "python-docx>=1.1.2",
]
